### PR TITLE
Break up the TOC into categories to give structure

### PR DESCRIPTION
**Pull request by brianjking**

### CODE REVIEW

**Comment by brianjking** [comment]
@AnoopAlias -- I think you need to adjust your readthedcs build settings as the PRs you've merged are not reflected there.

**Comment by AnoopAlias** [comment]
@brianjking - I had reverted that as the section headings are not shown somehow. I think it needs the sub-headings in a separate folder with another index.rst in it ? I am new to restructured text so not very sure about the syntax .
The docs were manually pulled over to readthedocs but it looked the same as before without the sections you added.

**Comment by brianjking** [comment]
I'll fix it tomorrow, sorry. I use Sphinx often so I can take care of it.

Sorry about that.

Thank you,

Brian J King

**Comment by AnoopAlias** [comment]
@brianjking - I have readded your patch. Probably it's a problem with readthedocs as I don't see my new doc additions even after the doc build is showing as passing . I even tried changing the theme which is also not being picked up. Probably somethings up with readthedocs and I will wait for a day to see if things are working as expected

**Comment by brianjking** [comment]
@AnoopAlias Yup, looks like RTD just likely got stuck in the build process as they've all completed as seen @ https://readthedocs.org/projects/ndeploy/builds/. 

_I suggest changing the theme back to ReadTheDocs default theme instead of Alabaster or whatever is being used now._

**Comment by AnoopAlias** [comment]
@brianjking changed the theme to RTD one.

**Pull request merged**
